package com.megalink.study.mappers.nochange;

import com.megalink.study.model.nochange.Hansen;
import com.megalink.study.model.nochange.HansenExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface MBGHansenMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hansen02
     *
     * @mbggenerated
     */
    int countByExample(HansenExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hansen02
     *
     * @mbggenerated
     */
    int deleteByExample(HansenExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hansen02
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hansen02
     *
     * @mbggenerated
     */
    int insert(Hansen record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hansen02
     *
     * @mbggenerated
     */
    int insertSelective(Hansen record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hansen02
     *
     * @mbggenerated
     */
    List<Hansen> selectByExample(HansenExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hansen02
     *
     * @mbggenerated
     */
    Hansen selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hansen02
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") Hansen record, @Param("example") HansenExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hansen02
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") Hansen record, @Param("example") HansenExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hansen02
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Hansen record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hansen02
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Hansen record);
}